import type {
  AiRecommendation,
  DisasterZone,
  DroneMission,
  EmergencyResource,
  Hospital,
  Incident,
  ReliefCenter,
  RoadSegment,
  SystemAlert,
} from "./types";

/**
 * SIMULATED baseline dataset for the Bengaluru / Karnataka prototype.
 * Values are fictional and used for demonstration only.
 */

export const SIM_EPOCH = Date.parse("2026-08-14T13:40:00+05:30");

/** Deterministic timestamp helper so SSR and client render identically. */
export const t = (minutesAgo: number) => new Date(SIM_EPOCH - minutesAgo * 60_000).toISOString();

export const CITIZEN_LOCATION = { area: "Koramangala, Bengaluru", lat: 12.9352, lng: 77.6245 };

export const seedHospitals: Hospital[] = [
  {
    id: "H1",
    name: "Koramangala City Hospital",
    area: "Koramangala",
    location: { lat: 12.9301, lng: 77.6301 },
    status: "operational",
    emergencyBeds: { used: 18, total: 30 },
    icu: { used: 8, total: 20 },
    oxygenPct: 76,
    bloodUnits: 44,
    ambulances: 4,
    ambulancesAvailable: 3,
    accessAffected: false,
    floodRisk: "medium",
    updatedAt: t(4),
  },
  {
    id: "H2",
    name: "Jayanagar General Hospital",
    area: "Jayanagar",
    location: { lat: 12.925, lng: 77.5938 },
    status: "operational",
    emergencyBeds: { used: 12, total: 40 },
    icu: { used: 6, total: 24 },
    oxygenPct: 88,
    bloodUnits: 61,
    ambulances: 6,
    ambulancesAvailable: 4,
    accessAffected: false,
    floodRisk: "low",
    updatedAt: t(7),
  },
  {
    id: "H3",
    name: "HSR Layout Multi-Speciality",
    area: "HSR Layout",
    location: { lat: 12.9116, lng: 77.6474 },
    status: "limited",
    emergencyBeds: { used: 26, total: 28 },
    icu: { used: 15, total: 16 },
    oxygenPct: 41,
    bloodUnits: 18,
    ambulances: 3,
    ambulancesAvailable: 1,
    accessAffected: false,
    floodRisk: "high",
    updatedAt: t(2),
  },
  {
    id: "H4",
    name: "KR Puram Trauma Centre",
    area: "KR Puram",
    location: { lat: 13.0068, lng: 77.696 },
    status: "operational",
    emergencyBeds: { used: 9, total: 22 },
    icu: { used: 4, total: 12 },
    oxygenPct: 82,
    bloodUnits: 33,
    ambulances: 3,
    ambulancesAvailable: 2,
    accessAffected: false,
    floodRisk: "high",
    updatedAt: t(11),
  },
  {
    id: "H5",
    name: "Indiranagar Emergency Care",
    area: "Indiranagar",
    location: { lat: 12.9719, lng: 77.6412 },
    status: "operational",
    emergencyBeds: { used: 14, total: 26 },
    icu: { used: 7, total: 14 },
    oxygenPct: 69,
    bloodUnits: 27,
    ambulances: 4,
    ambulancesAvailable: 3,
    accessAffected: false,
    floodRisk: "low",
    updatedAt: t(9),
  },
  {
    id: "H6",
    name: "Bellandur Community Hospital",
    area: "Bellandur",
    location: { lat: 12.9304, lng: 77.6784 },
    status: "operational",
    emergencyBeds: { used: 7, total: 18 },
    icu: { used: 3, total: 8 },
    oxygenPct: 74,
    bloodUnits: 21,
    ambulances: 2,
    ambulancesAvailable: 2,
    accessAffected: false,
    floodRisk: "medium",
    updatedAt: t(15),
  },
];

export const seedReliefCenters: ReliefCenter[] = [
  {
    id: "R04",
    name: "Koramangala Indoor Stadium Relief Camp",
    area: "Koramangala",
    location: { lat: 12.9385, lng: 77.6189 },
    capacity: 600,
    occupancy: 214,
    food: "adequate",
    water: "adequate",
    medicalSupport: true,
    status: "open",
    updatedAt: t(6),
  },
  {
    id: "R07",
    name: "Bellandur Government School Camp",
    area: "Bellandur",
    location: { lat: 12.9268, lng: 77.6731 },
    capacity: 400,
    occupancy: 318,
    food: "low",
    water: "adequate",
    medicalSupport: true,
    status: "filling",
    updatedAt: t(3),
  },
  {
    id: "R08",
    name: "KR Puram Community Hall",
    area: "KR Puram",
    location: { lat: 13.0031, lng: 77.6897 },
    capacity: 250,
    occupancy: 61,
    food: "adequate",
    water: "low",
    medicalSupport: false,
    status: "open",
    updatedAt: t(12),
  },
  {
    id: "R11",
    name: "HSR Sector 2 Shelter",
    area: "HSR Layout",
    location: { lat: 12.9081, lng: 77.6412 },
    capacity: 320,
    occupancy: 96,
    food: "adequate",
    water: "adequate",
    medicalSupport: true,
    status: "open",
    updatedAt: t(18),
  },
];

export const seedResources: EmergencyResource[] = [
  { id: "A04", callSign: "Ambulance A04", type: "Ambulance", area: "Koramangala", location: { lat: 12.9339, lng: 77.6205 }, status: "available", crew: 3, homeBase: "H1" },
  { id: "A12", callSign: "Ambulance A12", type: "Ambulance", area: "HSR Layout", location: { lat: 12.9128, lng: 77.6428 }, status: "available", crew: 3, homeBase: "H3" },
  { id: "A18", callSign: "Ambulance A18", type: "Ambulance", area: "Jayanagar", location: { lat: 12.9271, lng: 77.5901 }, status: "available", crew: 2, homeBase: "H2" },
  { id: "A21", callSign: "Ambulance A21", type: "Ambulance", area: "Indiranagar", location: { lat: 12.9702, lng: 77.6398 }, status: "en_route", crew: 3, homeBase: "H5", etaMinutes: 8 },
  { id: "A26", callSign: "Ambulance A26", type: "Ambulance", area: "KR Puram", location: { lat: 13.0042, lng: 77.6942 }, status: "available", crew: 3, homeBase: "H4" },
  { id: "R02", callSign: "Rescue Team R02", type: "Rescue Team", area: "Bellandur", location: { lat: 12.9288, lng: 77.6752 }, status: "available", crew: 8, homeBase: "Bellandur Depot" },
  { id: "R04", callSign: "Rescue Team R04", type: "Rescue Team", area: "Koramangala", location: { lat: 12.9366, lng: 77.6262 }, status: "available", crew: 9, homeBase: "City Depot" },
  { id: "R12", callSign: "Rescue Team R12", type: "Rescue Team", area: "KR Puram", location: { lat: 13.0011, lng: 77.6889 }, status: "available", crew: 10, homeBase: "East Depot" },
  { id: "F03", callSign: "Fire Unit F03", type: "Fire Truck", area: "Indiranagar", location: { lat: 12.9741, lng: 77.6377 }, status: "available", crew: 6, homeBase: "Indiranagar Fire Station" },
  { id: "F09", callSign: "Fire Unit F09", type: "Fire Truck", area: "Jayanagar", location: { lat: 12.9229, lng: 77.5966 }, status: "busy", crew: 6, homeBase: "South Fire Station" },
  { id: "P07", callSign: "Police Unit P07", type: "Police Unit", area: "Koramangala", location: { lat: 12.9318, lng: 77.6288 }, status: "available", crew: 4, homeBase: "Koramangala PS" },
  { id: "P14", callSign: "Police Unit P14", type: "Police Unit", area: "Bellandur", location: { lat: 12.9331, lng: 77.6801 }, status: "assigned", crew: 4, homeBase: "Bellandur PS" },
  { id: "B02", callSign: "Rescue Boat B02", type: "Boat", area: "Bellandur", location: { lat: 12.9251, lng: 77.6712 }, status: "available", crew: 4, homeBase: "Lake Command" },
  { id: "D04", callSign: "Drone D04", type: "Drone", area: "KR Puram", location: { lat: 13.0059, lng: 77.6921 }, status: "busy", crew: 0, homeBase: "East Depot" },
  { id: "M05", callSign: "Medical Team M05", type: "Medical Team", area: "HSR Layout", location: { lat: 12.9098, lng: 77.6449 }, status: "available", crew: 5, homeBase: "H3" },
  { id: "M09", callSign: "Medical Team M09", type: "Medical Team", area: "Koramangala", location: { lat: 12.9372, lng: 77.6221 }, status: "offline", crew: 5, homeBase: "H1" },
];

export const seedRoads: RoadSegment[] = [
  { id: "RD-11", name: "Road 11 · Sarjapur Main Road", from: { lat: 12.9231, lng: 77.6412 }, to: { lat: 12.9109, lng: 77.6801 }, status: "clear", severity: "low", updatedAt: t(20) },
  { id: "RD-14", name: "Road 14 · Ejipura Link Road", from: { lat: 12.9351, lng: 77.6229 }, to: { lat: 12.9218, lng: 77.6314 }, status: "flood_affected", severity: "high", updatedAt: t(5), note: "Water logging 0.6 m near underpass" },
  { id: "RD-17", name: "Road 17 · Outer Ring Road (Bellandur)", from: { lat: 12.9271, lng: 77.6704 }, to: { lat: 12.9522, lng: 77.6971 }, status: "clear", severity: "medium", updatedAt: t(14) },
  { id: "RD-22", name: "Road 22 · Old Madras Road", from: { lat: 12.9891, lng: 77.6668 }, to: { lat: 13.0071, lng: 77.6989 }, status: "clear", severity: "low", updatedAt: t(25) },
  { id: "RD-29", name: "Road 29 · Hosur Road Service Lane", from: { lat: 12.9214, lng: 77.6098 }, to: { lat: 12.9002, lng: 77.6221 }, status: "clear", severity: "low", updatedAt: t(31) },
  { id: "RD-35", name: "Road 35 · 100 Ft Road Indiranagar", from: { lat: 12.9702, lng: 77.6402 }, to: { lat: 12.9601, lng: 77.6489 }, status: "clear", severity: "low", updatedAt: t(28) },
];

export const seedZones: DisasterZone[] = [
  { id: "Z4", name: "Zone 4 · Bellandur Lake Basin", area: "Bellandur", center: { lat: 12.9298, lng: 77.6742 }, radiusKm: 1.9, hazard: "flood", risk: "medium", populationExposed: 18400, evacuationRecommended: false },
  { id: "Z7", name: "Zone 7 · KR Puram Low-lying", area: "KR Puram", center: { lat: 13.0041, lng: 77.6931 }, radiusKm: 1.6, hazard: "flood", risk: "high", populationExposed: 12600, evacuationRecommended: false },
];

export const seedIncidents: Incident[] = [
  {
    id: "PRG-10284",
    type: "Trapped Person",
    severity: "critical",
    area: "Koramangala",
    location: { lat: 12.9337, lng: 77.6271 },
    description: "Two residents reported trapped on ground floor of apartment basement, water rising.",
    peopleAffected: 2,
    reportedAt: t(9),
    status: "awaiting",
    source: "citizen",
    photoCount: 2,
    timeline: [
      { at: t(9), label: "Citizen request received", actor: "Citizen Portal" },
      { at: t(8), label: "Auto-triaged as Critical", actor: "PRAGATI triage rules" },
    ],
  },
  {
    id: "PRG-10291",
    type: "Medical Emergency",
    severity: "critical",
    area: "HSR Layout",
    location: { lat: 12.9142, lng: 77.6455 },
    description: "Elderly patient with breathing difficulty, road access uncertain.",
    peopleAffected: 1,
    reportedAt: t(14),
    status: "awaiting",
    source: "citizen",
    timeline: [{ at: t(14), label: "Citizen request received", actor: "Citizen Portal" }],
  },
  {
    id: "PRG-10295",
    type: "Flood",
    severity: "high",
    area: "Bellandur",
    location: { lat: 12.9283, lng: 77.6721 },
    description: "Street-level flooding in 3 lanes, 40+ households requesting evacuation support.",
    peopleAffected: 46,
    reportedAt: t(22),
    status: "awaiting",
    source: "field_team",
    timeline: [{ at: t(22), label: "Field team report logged", actor: "Ward Officer" }],
  },
  {
    id: "PRG-10299",
    type: "Road Blockage",
    severity: "medium",
    area: "Koramangala",
    location: { lat: 12.9291, lng: 77.6299 },
    description: "Uprooted tree blocking Ejipura link road carriageway.",
    peopleAffected: 0,
    reportedAt: t(28),
    status: "assigned",
    assignedResourceId: "P07",
    etaMinutes: 11,
    source: "police",
    timeline: [
      { at: t(28), label: "Reported by patrol", actor: "Koramangala PS" },
      { at: t(24), label: "Police Unit P07 assigned", actor: "Command Center" },
    ],
  },
  {
    id: "PRG-10302",
    type: "Accident",
    severity: "high",
    area: "Indiranagar",
    location: { lat: 12.9688, lng: 77.6433 },
    description: "Two-vehicle collision at 100 Ft Road junction, 3 injuries reported.",
    peopleAffected: 3,
    reportedAt: t(17),
    status: "en_route",
    assignedResourceId: "A21",
    etaMinutes: 8,
    source: "citizen",
    timeline: [
      { at: t(17), label: "Citizen request received", actor: "Citizen Portal" },
      { at: t(15), label: "Ambulance A21 dispatched", actor: "Command Center" },
    ],
  },
  {
    id: "PRG-10305",
    type: "Fire",
    severity: "high",
    area: "Jayanagar",
    location: { lat: 12.9236, lng: 77.5972 },
    description: "Commercial kitchen fire, building evacuated, containment in progress.",
    peopleAffected: 12,
    reportedAt: t(35),
    status: "on_scene",
    assignedResourceId: "F09",
    etaMinutes: 0,
    source: "citizen",
    timeline: [
      { at: t(35), label: "Emergency call logged", actor: "112 Bridge (simulated)" },
      { at: t(31), label: "Fire Unit F09 on scene", actor: "Fire & Rescue" },
    ],
  },
  {
    id: "PRG-10308",
    type: "Building Damage",
    severity: "medium",
    area: "KR Puram",
    location: { lat: 13.0022, lng: 77.6912 },
    description: "Partial wall collapse of unoccupied structure after prolonged rainfall.",
    peopleAffected: 0,
    reportedAt: t(41),
    status: "assigned",
    assignedResourceId: "R12",
    etaMinutes: 14,
    source: "drone",
    timeline: [{ at: t(41), label: "Detected in drone survey D04", actor: "Field Intelligence" }],
  },
  {
    id: "PRG-10311",
    type: "Missing Person",
    severity: "high",
    area: "Bellandur",
    location: { lat: 12.9319, lng: 77.6769 },
    description: "Teenager missing since 12:40, last seen near flooded storm drain.",
    peopleAffected: 1,
    reportedAt: t(48),
    status: "assigned",
    assignedResourceId: "P14",
    etaMinutes: 6,
    source: "citizen",
    timeline: [{ at: t(48), label: "Citizen request received", actor: "Citizen Portal" }],
  },
  {
    id: "PRG-10314",
    type: "Medical Emergency",
    severity: "low",
    area: "Jayanagar",
    location: { lat: 12.9262, lng: 77.5924 },
    description: "Minor injury during relief distribution, first aid provided.",
    peopleAffected: 1,
    reportedAt: t(55),
    status: "resolved",
    source: "field_team",
    timeline: [{ at: t(55), label: "Logged by relief volunteer", actor: "R04" }],
  },
];

export const seedAlerts: SystemAlert[] = [
  { id: "AL-901", level: "warning", title: "Hospital H3 approaching emergency capacity", detail: "HSR Layout Multi-Speciality at 26/28 emergency beds and 15/16 ICU.", at: t(3), acknowledged: false, source: "Capacity Monitor" },
  { id: "AL-902", level: "warning", title: "Road 14 water logging reported", detail: "Ejipura link road water level 0.6 m; heavy vehicles advised to divert.", at: t(5), acknowledged: false, source: "Field Reports" },
  { id: "AL-903", level: "info", title: "Relief centre R08 opened", detail: "KR Puram Community Hall activated with capacity for 250 people.", at: t(12), acknowledged: true, source: "Relief Operations" },
  { id: "AL-904", level: "info", title: "Drone survey D04 launched over Zone 7", detail: "Simulated aerial survey covering KR Puram low-lying belt.", at: t(19), acknowledged: true, source: "Field Intelligence" },
];

export const seedRecommendations: AiRecommendation[] = [
  {
    id: "AI-5001",
    kind: "resource_allocation",
    headline: "Assign Rescue Team R04 to Incident PRG-10284",
    reason:
      "PRG-10284 is Critical with 2 people trapped and rising water. Rescue Team R04 is 1.4 km away, available, and its approach avoids Road 14 which is flood affected.",
    suggestedAction: "Dispatch Rescue Team R04 with boat support B02 on standby.",
    severity: "critical",
    at: t(7),
    confidence: 0.86,
    status: "pending",
    incidentId: "PRG-10284",
    resourceId: "R04",
    factors: [
      { label: "Severity", value: "Critical (weight 40%)" },
      { label: "Distance", value: "1.4 km" },
      { label: "People affected", value: "2" },
      { label: "Route risk", value: "Low (alternate lane)" },
    ],
  },
  {
    id: "AI-5002",
    kind: "capacity",
    headline: "Hospital H3 approaching emergency capacity",
    reason:
      "HSR Layout Multi-Speciality has 2 emergency beds and 1 ICU bed remaining with oxygen at 41%. Continued intake risks refusal of critical cases.",
    suggestedAction: "Route new critical cases from HSR/Bellandur to Jayanagar General Hospital (H2).",
    severity: "high",
    at: t(3),
    confidence: 0.79,
    status: "pending",
    factors: [
      { label: "Emergency beds", value: "26 / 28" },
      { label: "ICU", value: "15 / 16" },
      { label: "Oxygen", value: "41%" },
    ],
  },
  {
    id: "AI-5003",
    kind: "hospital_routing",
    headline: "Prefer Hospital H2 over H1 for Koramangala critical cases",
    reason:
      "Hospital H1 is geographically closest to Incident PRG-10284, but its primary access via Road 14 is flood affected. Hospital H2 has a slightly longer route with lower risk and available emergency capacity.",
    suggestedAction: "Set Jayanagar General Hospital as preferred receiving facility for Koramangala until Road 14 clears.",
    severity: "high",
    at: t(6),
    confidence: 0.82,
    status: "pending",
    incidentId: "PRG-10284",
    factors: [
      { label: "H1 route risk", value: "High (Road 14)" },
      { label: "H2 route risk", value: "Low" },
      { label: "H2 emergency beds free", value: "28" },
    ],
  },
];

export const seedDrones: DroneMission[] = [
  {
    id: "DM-201",
    droneId: "D04",
    area: "KR Puram",
    location: { lat: 13.0059, lng: 77.6921 },
    status: "active",
    altitudeM: 92,
    batteryPct: 64,
    startedAt: t(19),
    detections: { peopleDetected: 17, vehiclesStranded: 3, damagedStructures: 2, floodSeverity: "high" },
  },
  {
    id: "DM-202",
    droneId: "D09",
    area: "Bellandur",
    location: { lat: 12.9282, lng: 77.6748 },
    status: "idle",
    altitudeM: 0,
    batteryPct: 97,
    startedAt: t(60),
    detections: null,
  },
  {
    id: "DM-203",
    droneId: "D11",
    area: "Koramangala",
    location: { lat: 12.9344, lng: 77.6248 },
    status: "charging",
    altitudeM: 0,
    batteryPct: 38,
    startedAt: t(120),
    detections: null,
  },
];