/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenHelpRouteImport } from './routes/citizen.help'
import { Route as CitizenHospitalsRouteImport } from './routes/citizen.hospitals'
import { Route as CitizenReliefCentersRouteImport } from './routes/citizen.relief-centers'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as CitizenRequestsRouteImport } from './routes/citizen.requests'
import { Route as CitizenSafeRouteRouteImport } from './routes/citizen.safe-route'
import { Route as CommandIndexRouteImport } from './routes/command.index'
import { Route as CommandAlertsRouteImport } from './routes/command.alerts'
import { Route as CommandDronesRouteImport } from './routes/command.drones'
import { Route as CommandHospitalsRouteImport } from './routes/command.hospitals'
import { Route as CommandIncidentsRouteImport } from './routes/command.incidents'
import { Route as CommandIntelligenceRouteImport } from './routes/command.intelligence'
import { Route as CommandMapRouteImport } from './routes/command.map'
import { Route as CommandReliefCentersRouteImport } from './routes/command.relief-centers'
import { Route as CommandResourcesRouteImport } from './routes/command.resources'
import { Route as CommandRoutesRouteImport } from './routes/command.routes'
import { Route as CommandSettingsRouteImport } from './routes/command.settings'
import { Route as CommandSimulatorRouteImport } from './routes/command.simulator'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as HospitalAmbulancesRouteImport } from './routes/hospital.ambulances'
import { Route as HospitalCapacityRouteImport } from './routes/hospital.capacity'
import { Route as HospitalRequestsRouteImport } from './routes/hospital.requests'
import { Route as HospitalUpdatesRouteImport } from './routes/hospital.updates'
import { Route as ReliefIndexRouteImport } from './routes/relief.index'
import { Route as ReliefOccupancyRouteImport } from './routes/relief.occupancy'
import { Route as ReliefUpdatesRouteImport } from './routes/relief.updates'
import { Route as ResponderIndexRouteImport } from './routes/responder.index'
import { Route as ResponderIncidentsRouteImport } from './routes/responder.incidents'
import { Route as ResponderRequestsRouteImport } from './routes/responder.requests'
import { Route as ResponderResourcesRouteImport } from './routes/responder.resources'
import { Route as ResponderRoutesRouteImport } from './routes/responder.routes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenHelpRoute = CitizenHelpRouteImport.update({
  id: '/citizen/help',
  path: '/citizen/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenHospitalsRoute = CitizenHospitalsRouteImport.update({
  id: '/citizen/hospitals',
  path: '/citizen/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReliefCentersRoute = CitizenReliefCentersRouteImport.update({
  id: '/citizen/relief-centers',
  path: '/citizen/relief-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRequestsRoute = CitizenRequestsRouteImport.update({
  id: '/citizen/requests',
  path: '/citizen/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenSafeRouteRoute = CitizenSafeRouteRouteImport.update({
  id: '/citizen/safe-route',
  path: '/citizen/safe-route',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIndexRoute = CommandIndexRouteImport.update({
  id: '/command/',
  path: '/command/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandAlertsRoute = CommandAlertsRouteImport.update({
  id: '/command/alerts',
  path: '/command/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandDronesRoute = CommandDronesRouteImport.update({
  id: '/command/drones',
  path: '/command/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandHospitalsRoute = CommandHospitalsRouteImport.update({
  id: '/command/hospitals',
  path: '/command/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIncidentsRoute = CommandIncidentsRouteImport.update({
  id: '/command/incidents',
  path: '/command/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIntelligenceRoute = CommandIntelligenceRouteImport.update({
  id: '/command/intelligence',
  path: '/command/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandMapRoute = CommandMapRouteImport.update({
  id: '/command/map',
  path: '/command/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandReliefCentersRoute = CommandReliefCentersRouteImport.update({
  id: '/command/relief-centers',
  path: '/command/relief-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandResourcesRoute = CommandResourcesRouteImport.update({
  id: '/command/resources',
  path: '/command/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoutesRoute = CommandRoutesRouteImport.update({
  id: '/command/routes',
  path: '/command/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandSettingsRoute = CommandSettingsRouteImport.update({
  id: '/command/settings',
  path: '/command/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandSimulatorRoute = CommandSimulatorRouteImport.update({
  id: '/command/simulator',
  path: '/command/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/hospital/',
  path: '/hospital/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAmbulancesRoute = HospitalAmbulancesRouteImport.update({
  id: '/hospital/ambulances',
  path: '/hospital/ambulances',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalCapacityRoute = HospitalCapacityRouteImport.update({
  id: '/hospital/capacity',
  path: '/hospital/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRequestsRoute = HospitalRequestsRouteImport.update({
  id: '/hospital/requests',
  path: '/hospital/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalUpdatesRoute = HospitalUpdatesRouteImport.update({
  id: '/hospital/updates',
  path: '/hospital/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliefIndexRoute = ReliefIndexRouteImport.update({
  id: '/relief/',
  path: '/relief/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliefOccupancyRoute = ReliefOccupancyRouteImport.update({
  id: '/relief/occupancy',
  path: '/relief/occupancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliefUpdatesRoute = ReliefUpdatesRouteImport.update({
  id: '/relief/updates',
  path: '/relief/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderIndexRoute = ResponderIndexRouteImport.update({
  id: '/responder/',
  path: '/responder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderIncidentsRoute = ResponderIncidentsRouteImport.update({
  id: '/responder/incidents',
  path: '/responder/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderRequestsRoute = ResponderRequestsRouteImport.update({
  id: '/responder/requests',
  path: '/responder/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderResourcesRoute = ResponderResourcesRouteImport.update({
  id: '/responder/resources',
  path: '/responder/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderRoutesRoute = ResponderRoutesRouteImport.update({
  id: '/responder/routes',
  path: '/responder/routes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen/help': typeof CitizenHelpRoute
  '/citizen/hospitals': typeof CitizenHospitalsRoute
  '/citizen/relief-centers': typeof CitizenReliefCentersRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/requests': typeof CitizenRequestsRoute
  '/citizen/safe-route': typeof CitizenSafeRouteRoute
  '/command/alerts': typeof CommandAlertsRoute
  '/command/drones': typeof CommandDronesRoute
  '/command/hospitals': typeof CommandHospitalsRoute
  '/command/incidents': typeof CommandIncidentsRoute
  '/command/intelligence': typeof CommandIntelligenceRoute
  '/command/map': typeof CommandMapRoute
  '/command/relief-centers': typeof CommandReliefCentersRoute
  '/command/resources': typeof CommandResourcesRoute
  '/command/routes': typeof CommandRoutesRoute
  '/command/settings': typeof CommandSettingsRoute
  '/command/simulator': typeof CommandSimulatorRoute
  '/hospital/ambulances': typeof HospitalAmbulancesRoute
  '/hospital/capacity': typeof HospitalCapacityRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/hospital/updates': typeof HospitalUpdatesRoute
  '/relief/occupancy': typeof ReliefOccupancyRoute
  '/relief/updates': typeof ReliefUpdatesRoute
  '/responder/incidents': typeof ResponderIncidentsRoute
  '/responder/requests': typeof ResponderRequestsRoute
  '/responder/resources': typeof ResponderResourcesRoute
  '/responder/routes': typeof ResponderRoutesRoute
  '/citizen/': typeof CitizenIndexRoute
  '/command/': typeof CommandIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/relief/': typeof ReliefIndexRoute
  '/responder/': typeof ResponderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen/help': typeof CitizenHelpRoute
  '/citizen/hospitals': typeof CitizenHospitalsRoute
  '/citizen/relief-centers': typeof CitizenReliefCentersRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/requests': typeof CitizenRequestsRoute
  '/citizen/safe-route': typeof CitizenSafeRouteRoute
  '/command/alerts': typeof CommandAlertsRoute
  '/command/drones': typeof CommandDronesRoute
  '/command/hospitals': typeof CommandHospitalsRoute
  '/command/incidents': typeof CommandIncidentsRoute
  '/command/intelligence': typeof CommandIntelligenceRoute
  '/command/map': typeof CommandMapRoute
  '/command/relief-centers': typeof CommandReliefCentersRoute
  '/command/resources': typeof CommandResourcesRoute
  '/command/routes': typeof CommandRoutesRoute
  '/command/settings': typeof CommandSettingsRoute
  '/command/simulator': typeof CommandSimulatorRoute
  '/hospital/ambulances': typeof HospitalAmbulancesRoute
  '/hospital/capacity': typeof HospitalCapacityRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/hospital/updates': typeof HospitalUpdatesRoute
  '/relief/occupancy': typeof ReliefOccupancyRoute
  '/relief/updates': typeof ReliefUpdatesRoute
  '/responder/incidents': typeof ResponderIncidentsRoute
  '/responder/requests': typeof ResponderRequestsRoute
  '/responder/resources': typeof ResponderResourcesRoute
  '/responder/routes': typeof ResponderRoutesRoute
  '/citizen': typeof CitizenIndexRoute
  '/command': typeof CommandIndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/relief': typeof ReliefIndexRoute
  '/responder': typeof ResponderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen/help': typeof CitizenHelpRoute
  '/citizen/hospitals': typeof CitizenHospitalsRoute
  '/citizen/relief-centers': typeof CitizenReliefCentersRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/requests': typeof CitizenRequestsRoute
  '/citizen/safe-route': typeof CitizenSafeRouteRoute
  '/command/alerts': typeof CommandAlertsRoute
  '/command/drones': typeof CommandDronesRoute
  '/command/hospitals': typeof CommandHospitalsRoute
  '/command/incidents': typeof CommandIncidentsRoute
  '/command/intelligence': typeof CommandIntelligenceRoute
  '/command/map': typeof CommandMapRoute
  '/command/relief-centers': typeof CommandReliefCentersRoute
  '/command/resources': typeof CommandResourcesRoute
  '/command/routes': typeof CommandRoutesRoute
  '/command/settings': typeof CommandSettingsRoute
  '/command/simulator': typeof CommandSimulatorRoute
  '/hospital/ambulances': typeof HospitalAmbulancesRoute
  '/hospital/capacity': typeof HospitalCapacityRoute
  '/hospital/requests': typeof HospitalRequestsRoute
  '/hospital/updates': typeof HospitalUpdatesRoute
  '/relief/occupancy': typeof ReliefOccupancyRoute
  '/relief/updates': typeof ReliefUpdatesRoute
  '/responder/incidents': typeof ResponderIncidentsRoute
  '/responder/requests': typeof ResponderRequestsRoute
  '/responder/resources': typeof ResponderResourcesRoute
  '/responder/routes': typeof ResponderRoutesRoute
  '/citizen/': typeof CitizenIndexRoute
  '/command/': typeof CommandIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/relief/': typeof ReliefIndexRoute
  '/responder/': typeof ResponderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen/help'
    | '/citizen/hospitals'
    | '/citizen/relief-centers'
    | '/citizen/report'
    | '/citizen/requests'
    | '/citizen/safe-route'
    | '/command/alerts'
    | '/command/drones'
    | '/command/hospitals'
    | '/command/incidents'
    | '/command/intelligence'
    | '/command/map'
    | '/command/relief-centers'
    | '/command/resources'
    | '/command/routes'
    | '/command/settings'
    | '/command/simulator'
    | '/hospital/ambulances'
    | '/hospital/capacity'
    | '/hospital/requests'
    | '/hospital/updates'
    | '/relief/occupancy'
    | '/relief/updates'
    | '/responder/incidents'
    | '/responder/requests'
    | '/responder/resources'
    | '/responder/routes'
    | '/citizen/'
    | '/command/'
    | '/hospital/'
    | '/relief/'
    | '/responder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen/help'
    | '/citizen/hospitals'
    | '/citizen/relief-centers'
    | '/citizen/report'
    | '/citizen/requests'
    | '/citizen/safe-route'
    | '/command/alerts'
    | '/command/drones'
    | '/command/hospitals'
    | '/command/incidents'
    | '/command/intelligence'
    | '/command/map'
    | '/command/relief-centers'
    | '/command/resources'
    | '/command/routes'
    | '/command/settings'
    | '/command/simulator'
    | '/hospital/ambulances'
    | '/hospital/capacity'
    | '/hospital/requests'
    | '/hospital/updates'
    | '/relief/occupancy'
    | '/relief/updates'
    | '/responder/incidents'
    | '/responder/requests'
    | '/responder/resources'
    | '/responder/routes'
    | '/citizen'
    | '/command'
    | '/hospital'
    | '/relief'
    | '/responder'
  id:
    | '__root__'
    | '/'
    | '/citizen/help'
    | '/citizen/hospitals'
    | '/citizen/relief-centers'
    | '/citizen/report'
    | '/citizen/requests'
    | '/citizen/safe-route'
    | '/command/alerts'
    | '/command/drones'
    | '/command/hospitals'
    | '/command/incidents'
    | '/command/intelligence'
    | '/command/map'
    | '/command/relief-centers'
    | '/command/resources'
    | '/command/routes'
    | '/command/settings'
    | '/command/simulator'
    | '/hospital/ambulances'
    | '/hospital/capacity'
    | '/hospital/requests'
    | '/hospital/updates'
    | '/relief/occupancy'
    | '/relief/updates'
    | '/responder/incidents'
    | '/responder/requests'
    | '/responder/resources'
    | '/responder/routes'
    | '/citizen/'
    | '/command/'
    | '/hospital/'
    | '/relief/'
    | '/responder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenHelpRoute: typeof CitizenHelpRoute
  CitizenHospitalsRoute: typeof CitizenHospitalsRoute
  CitizenReliefCentersRoute: typeof CitizenReliefCentersRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenRequestsRoute: typeof CitizenRequestsRoute
  CitizenSafeRouteRoute: typeof CitizenSafeRouteRoute
  CommandAlertsRoute: typeof CommandAlertsRoute
  CommandDronesRoute: typeof CommandDronesRoute
  CommandHospitalsRoute: typeof CommandHospitalsRoute
  CommandIncidentsRoute: typeof CommandIncidentsRoute
  CommandIntelligenceRoute: typeof CommandIntelligenceRoute
  CommandMapRoute: typeof CommandMapRoute
  CommandReliefCentersRoute: typeof CommandReliefCentersRoute
  CommandResourcesRoute: typeof CommandResourcesRoute
  CommandRoutesRoute: typeof CommandRoutesRoute
  CommandSettingsRoute: typeof CommandSettingsRoute
  CommandSimulatorRoute: typeof CommandSimulatorRoute
  HospitalAmbulancesRoute: typeof HospitalAmbulancesRoute
  HospitalCapacityRoute: typeof HospitalCapacityRoute
  HospitalRequestsRoute: typeof HospitalRequestsRoute
  HospitalUpdatesRoute: typeof HospitalUpdatesRoute
  ReliefOccupancyRoute: typeof ReliefOccupancyRoute
  ReliefUpdatesRoute: typeof ReliefUpdatesRoute
  ResponderIncidentsRoute: typeof ResponderIncidentsRoute
  ResponderRequestsRoute: typeof ResponderRequestsRoute
  ResponderResourcesRoute: typeof ResponderResourcesRoute
  ResponderRoutesRoute: typeof ResponderRoutesRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  CommandIndexRoute: typeof CommandIndexRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
  ReliefIndexRoute: typeof ReliefIndexRoute
  ResponderIndexRoute: typeof ResponderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/help': {
      id: '/citizen/help'
      path: '/citizen/help'
      fullPath: '/citizen/help'
      preLoaderRoute: typeof CitizenHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/hospitals': {
      id: '/citizen/hospitals'
      path: '/citizen/hospitals'
      fullPath: '/citizen/hospitals'
      preLoaderRoute: typeof CitizenHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/relief-centers': {
      id: '/citizen/relief-centers'
      path: '/citizen/relief-centers'
      fullPath: '/citizen/relief-centers'
      preLoaderRoute: typeof CitizenReliefCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/requests': {
      id: '/citizen/requests'
      path: '/citizen/requests'
      fullPath: '/citizen/requests'
      preLoaderRoute: typeof CitizenRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/safe-route': {
      id: '/citizen/safe-route'
      path: '/citizen/safe-route'
      fullPath: '/citizen/safe-route'
      preLoaderRoute: typeof CitizenSafeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/': {
      id: '/command/'
      path: '/command'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/alerts': {
      id: '/command/alerts'
      path: '/command/alerts'
      fullPath: '/command/alerts'
      preLoaderRoute: typeof CommandAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/drones': {
      id: '/command/drones'
      path: '/command/drones'
      fullPath: '/command/drones'
      preLoaderRoute: typeof CommandDronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/hospitals': {
      id: '/command/hospitals'
      path: '/command/hospitals'
      fullPath: '/command/hospitals'
      preLoaderRoute: typeof CommandHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/incidents': {
      id: '/command/incidents'
      path: '/command/incidents'
      fullPath: '/command/incidents'
      preLoaderRoute: typeof CommandIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/intelligence': {
      id: '/command/intelligence'
      path: '/command/intelligence'
      fullPath: '/command/intelligence'
      preLoaderRoute: typeof CommandIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/map': {
      id: '/command/map'
      path: '/command/map'
      fullPath: '/command/map'
      preLoaderRoute: typeof CommandMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/relief-centers': {
      id: '/command/relief-centers'
      path: '/command/relief-centers'
      fullPath: '/command/relief-centers'
      preLoaderRoute: typeof CommandReliefCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/resources': {
      id: '/command/resources'
      path: '/command/resources'
      fullPath: '/command/resources'
      preLoaderRoute: typeof CommandResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/routes': {
      id: '/command/routes'
      path: '/command/routes'
      fullPath: '/command/routes'
      preLoaderRoute: typeof CommandRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/settings': {
      id: '/command/settings'
      path: '/command/settings'
      fullPath: '/command/settings'
      preLoaderRoute: typeof CommandSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/simulator': {
      id: '/command/simulator'
      path: '/command/simulator'
      fullPath: '/command/simulator'
      preLoaderRoute: typeof CommandSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/hospital'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/ambulances': {
      id: '/hospital/ambulances'
      path: '/hospital/ambulances'
      fullPath: '/hospital/ambulances'
      preLoaderRoute: typeof HospitalAmbulancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/capacity': {
      id: '/hospital/capacity'
      path: '/hospital/capacity'
      fullPath: '/hospital/capacity'
      preLoaderRoute: typeof HospitalCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/requests': {
      id: '/hospital/requests'
      path: '/hospital/requests'
      fullPath: '/hospital/requests'
      preLoaderRoute: typeof HospitalRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/updates': {
      id: '/hospital/updates'
      path: '/hospital/updates'
      fullPath: '/hospital/updates'
      preLoaderRoute: typeof HospitalUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relief/': {
      id: '/relief/'
      path: '/relief'
      fullPath: '/relief/'
      preLoaderRoute: typeof ReliefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relief/occupancy': {
      id: '/relief/occupancy'
      path: '/relief/occupancy'
      fullPath: '/relief/occupancy'
      preLoaderRoute: typeof ReliefOccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relief/updates': {
      id: '/relief/updates'
      path: '/relief/updates'
      fullPath: '/relief/updates'
      preLoaderRoute: typeof ReliefUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/': {
      id: '/responder/'
      path: '/responder'
      fullPath: '/responder/'
      preLoaderRoute: typeof ResponderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/incidents': {
      id: '/responder/incidents'
      path: '/responder/incidents'
      fullPath: '/responder/incidents'
      preLoaderRoute: typeof ResponderIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/requests': {
      id: '/responder/requests'
      path: '/responder/requests'
      fullPath: '/responder/requests'
      preLoaderRoute: typeof ResponderRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/resources': {
      id: '/responder/resources'
      path: '/responder/resources'
      fullPath: '/responder/resources'
      preLoaderRoute: typeof ResponderResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/routes': {
      id: '/responder/routes'
      path: '/responder/routes'
      fullPath: '/responder/routes'
      preLoaderRoute: typeof ResponderRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenHelpRoute: CitizenHelpRoute,
  CitizenHospitalsRoute: CitizenHospitalsRoute,
  CitizenReliefCentersRoute: CitizenReliefCentersRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenRequestsRoute: CitizenRequestsRoute,
  CitizenSafeRouteRoute: CitizenSafeRouteRoute,
  CommandAlertsRoute: CommandAlertsRoute,
  CommandDronesRoute: CommandDronesRoute,
  CommandHospitalsRoute: CommandHospitalsRoute,
  CommandIncidentsRoute: CommandIncidentsRoute,
  CommandIntelligenceRoute: CommandIntelligenceRoute,
  CommandMapRoute: CommandMapRoute,
  CommandReliefCentersRoute: CommandReliefCentersRoute,
  CommandResourcesRoute: CommandResourcesRoute,
  CommandRoutesRoute: CommandRoutesRoute,
  CommandSettingsRoute: CommandSettingsRoute,
  CommandSimulatorRoute: CommandSimulatorRoute,
  HospitalAmbulancesRoute: HospitalAmbulancesRoute,
  HospitalCapacityRoute: HospitalCapacityRoute,
  HospitalRequestsRoute: HospitalRequestsRoute,
  HospitalUpdatesRoute: HospitalUpdatesRoute,
  ReliefOccupancyRoute: ReliefOccupancyRoute,
  ReliefUpdatesRoute: ReliefUpdatesRoute,
  ResponderIncidentsRoute: ResponderIncidentsRoute,
  ResponderRequestsRoute: ResponderRequestsRoute,
  ResponderResourcesRoute: ResponderResourcesRoute,
  ResponderRoutesRoute: ResponderRoutesRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  CommandIndexRoute: CommandIndexRoute,
  HospitalIndexRoute: HospitalIndexRoute,
  ReliefIndexRoute: ReliefIndexRoute,
  ResponderIndexRoute: ResponderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
